#![doc = "Peripheral access API for HC32F448 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn IRQ000_Handler();
    fn IRQ001_Handler();
    fn IRQ002_Handler();
    fn IRQ003_Handler();
    fn IRQ004_Handler();
    fn IRQ005_Handler();
    fn IRQ006_Handler();
    fn IRQ007_Handler();
    fn IRQ008_Handler();
    fn IRQ009_Handler();
    fn IRQ010_Handler();
    fn IRQ011_Handler();
    fn IRQ012_Handler();
    fn IRQ013_Handler();
    fn IRQ014_Handler();
    fn IRQ015_Handler();
    fn EXTINT00_SWINT16_Handler();
    fn EXTINT01_SWINT17_Handler();
    fn EXTINT02_SWINT18_Handler();
    fn EXTINT03_SWINT19_Handler();
    fn EXTINT04_SWINT20_Handler();
    fn EXTINT05_SWINT21_Handler();
    fn EXTINT06_SWINT22_Handler();
    fn EXTINT07_SWINT23_Handler();
    fn EXTINT08_SWINT24_Handler();
    fn EXTINT09_SWINT25_Handler();
    fn EXTINT10_SWINT26_Handler();
    fn EXTINT11_SWINT27_Handler();
    fn EXTINT12_SWINT28_Handler();
    fn EXTINT13_SWINT29_Handler();
    fn EXTINT14_SWINT30_Handler();
    fn EXTINT15_SWINT31_Handler();
    fn DMA1_Error_Handler();
    fn DMA1_TC0_BTC0_Handler();
    fn DMA1_TC1_BTC1_Handler();
    fn DMA1_TC2_BTC2_Handler();
    fn DMA1_TC3_BTC3_Handler();
    fn DMA1_TC4_BTC4_Handler();
    fn DMA1_TC5_BTC5_Handler();
    fn EFM_PEError_ReadCol_Handler();
    fn EFM_OpEnd_Handler();
    fn QSPI_Handler();
    fn DCU1_Handler();
    fn DCU2_Handler();
    fn DCU3_Handler();
    fn DCU4_Handler();
    fn DMA2_Error_Handler();
    fn DMA2_TC0_BTC0_Handler();
    fn DMA2_TC1_BTC1_Handler();
    fn DMA2_TC2_BTC2_Handler();
    fn DMA2_TC3_BTC3_Handler();
    fn DMA2_TC4_BTC4_Handler();
    fn DMA2_TC5_BTC5_Handler();
    fn TMR0_1_Handler();
    fn TMR0_2_Handler();
    fn RTC_Handler();
    fn CLK_XtalStop_Handler();
    fn PWC_WKTM_Handler();
    fn SWDT_Handler();
    fn TMR6_1_GCmp_Handler();
    fn TMR6_1_Ovf_Udf_Handler();
    fn TMR6_1_Dte_Handler();
    fn TMR6_1_SCmp_Handler();
    fn TMRA_1_Ovf_Udf_Handler();
    fn TMRA_1_Cmp_Handler();
    fn TMR6_2_GCmp_Handler();
    fn TMR6_2_Ovf_Udf_Handler();
    fn TMR6_2_Dte_Handler();
    fn TMR6_2_SCmp_Handler();
    fn TMRA_2_Ovf_Udf_Handler();
    fn TMRA_2_Cmp_Handler();
    fn TMRA_3_Ovf_Udf_Handler();
    fn TMRA_3_Cmp_Handler();
    fn TMRA_4_Ovf_Udf_Handler();
    fn TMRA_4_Cmp_Handler();
    fn TMR4_1_GCmp_Handler();
    fn TMR4_1_Ovf_Udf_Handler();
    fn TMR4_1_Reload_Handler();
    fn TMR4_1_SCmp_Handler();
    fn TMR4_2_GCmp_Handler();
    fn TMR4_2_Ovf_Udf_Handler();
    fn TMR4_2_Reload_Handler();
    fn TMR4_2_SCmp_Handler();
    fn TMR4_3_GCmp_Handler();
    fn TMR4_3_Ovf_Udf_Handler();
    fn TMR4_3_Reload_Handler();
    fn TMR4_3_SCmp_Handler();
    fn I2C1_Handler();
    fn I2C2_Handler();
    fn CMP1_Handler();
    fn CMP2_Handler();
    fn CMP3_Handler();
    fn CMP4_Handler();
    fn USART1_Handler();
    fn USART1_TxComplete_Handler();
    fn USART2_Handler();
    fn USART2_TxComplete_Handler();
    fn SPI1_Handler();
    fn TMRA_5_Ovf_Udf_Handler();
    fn TMRA_5_Cmp_Handler();
    fn EVENT_PORT1_Handler();
    fn EVENT_PORT2_Handler();
    fn EVENT_PORT3_Handler();
    fn EVENT_PORT4_Handler();
    fn USART3_Handler();
    fn USART3_TxComplete_Handler();
    fn USART4_Handler();
    fn USART4_TxComplete_Handler();
    fn SPI2_Handler();
    fn SPI3_Handler();
    fn EMB_GR0_Handler();
    fn EMB_GR1_Handler();
    fn EMB_GR2_Handler();
    fn EMB_GR3_Handler();
    fn USART5_Handler();
    fn USART6_Handler();
    fn USART6_TxComplete_Handler();
    fn MCAN1_INT0_Handler();
    fn MCAN1_INT1_Handler();
    fn MCAN2_INT0_Handler();
    fn MCAN2_INT1_Handler();
    fn USART1_WKUP_Handler();
    fn PWC_LVD1_Handler();
    fn PWC_LVD2_Handler();
    fn FCM_Handler();
    fn WDT_Handler();
    fn CTC_Handler();
    fn ADC1_Handler();
    fn ADC2_Handler();
    fn ADC3_Handler();
    fn TRNG_Handler();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 132] = [
    Vector {
        _handler: IRQ000_Handler,
    },
    Vector {
        _handler: IRQ001_Handler,
    },
    Vector {
        _handler: IRQ002_Handler,
    },
    Vector {
        _handler: IRQ003_Handler,
    },
    Vector {
        _handler: IRQ004_Handler,
    },
    Vector {
        _handler: IRQ005_Handler,
    },
    Vector {
        _handler: IRQ006_Handler,
    },
    Vector {
        _handler: IRQ007_Handler,
    },
    Vector {
        _handler: IRQ008_Handler,
    },
    Vector {
        _handler: IRQ009_Handler,
    },
    Vector {
        _handler: IRQ010_Handler,
    },
    Vector {
        _handler: IRQ011_Handler,
    },
    Vector {
        _handler: IRQ012_Handler,
    },
    Vector {
        _handler: IRQ013_Handler,
    },
    Vector {
        _handler: IRQ014_Handler,
    },
    Vector {
        _handler: IRQ015_Handler,
    },
    Vector {
        _handler: EXTINT00_SWINT16_Handler,
    },
    Vector {
        _handler: EXTINT01_SWINT17_Handler,
    },
    Vector {
        _handler: EXTINT02_SWINT18_Handler,
    },
    Vector {
        _handler: EXTINT03_SWINT19_Handler,
    },
    Vector {
        _handler: EXTINT04_SWINT20_Handler,
    },
    Vector {
        _handler: EXTINT05_SWINT21_Handler,
    },
    Vector {
        _handler: EXTINT06_SWINT22_Handler,
    },
    Vector {
        _handler: EXTINT07_SWINT23_Handler,
    },
    Vector {
        _handler: EXTINT08_SWINT24_Handler,
    },
    Vector {
        _handler: EXTINT09_SWINT25_Handler,
    },
    Vector {
        _handler: EXTINT10_SWINT26_Handler,
    },
    Vector {
        _handler: EXTINT11_SWINT27_Handler,
    },
    Vector {
        _handler: EXTINT12_SWINT28_Handler,
    },
    Vector {
        _handler: EXTINT13_SWINT29_Handler,
    },
    Vector {
        _handler: EXTINT14_SWINT30_Handler,
    },
    Vector {
        _handler: EXTINT15_SWINT31_Handler,
    },
    Vector {
        _handler: DMA1_Error_Handler,
    },
    Vector {
        _handler: DMA1_TC0_BTC0_Handler,
    },
    Vector {
        _handler: DMA1_TC1_BTC1_Handler,
    },
    Vector {
        _handler: DMA1_TC2_BTC2_Handler,
    },
    Vector {
        _handler: DMA1_TC3_BTC3_Handler,
    },
    Vector {
        _handler: DMA1_TC4_BTC4_Handler,
    },
    Vector {
        _handler: DMA1_TC5_BTC5_Handler,
    },
    Vector {
        _handler: EFM_PEError_ReadCol_Handler,
    },
    Vector {
        _handler: EFM_OpEnd_Handler,
    },
    Vector {
        _handler: QSPI_Handler,
    },
    Vector {
        _handler: DCU1_Handler,
    },
    Vector {
        _handler: DCU2_Handler,
    },
    Vector {
        _handler: DCU3_Handler,
    },
    Vector {
        _handler: DCU4_Handler,
    },
    Vector {
        _handler: DMA2_Error_Handler,
    },
    Vector {
        _handler: DMA2_TC0_BTC0_Handler,
    },
    Vector {
        _handler: DMA2_TC1_BTC1_Handler,
    },
    Vector {
        _handler: DMA2_TC2_BTC2_Handler,
    },
    Vector {
        _handler: DMA2_TC3_BTC3_Handler,
    },
    Vector {
        _handler: DMA2_TC4_BTC4_Handler,
    },
    Vector {
        _handler: DMA2_TC5_BTC5_Handler,
    },
    Vector {
        _handler: TMR0_1_Handler,
    },
    Vector {
        _handler: TMR0_2_Handler,
    },
    Vector {
        _handler: RTC_Handler,
    },
    Vector {
        _handler: CLK_XtalStop_Handler,
    },
    Vector {
        _handler: PWC_WKTM_Handler,
    },
    Vector {
        _handler: SWDT_Handler,
    },
    Vector {
        _handler: TMR6_1_GCmp_Handler,
    },
    Vector {
        _handler: TMR6_1_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMR6_1_Dte_Handler,
    },
    Vector {
        _handler: TMR6_1_SCmp_Handler,
    },
    Vector {
        _handler: TMRA_1_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMRA_1_Cmp_Handler,
    },
    Vector {
        _handler: TMR6_2_GCmp_Handler,
    },
    Vector {
        _handler: TMR6_2_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMR6_2_Dte_Handler,
    },
    Vector {
        _handler: TMR6_2_SCmp_Handler,
    },
    Vector {
        _handler: TMRA_2_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMRA_2_Cmp_Handler,
    },
    Vector {
        _handler: TMRA_3_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMRA_3_Cmp_Handler,
    },
    Vector {
        _handler: TMRA_4_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMRA_4_Cmp_Handler,
    },
    Vector {
        _handler: TMR4_1_GCmp_Handler,
    },
    Vector {
        _handler: TMR4_1_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMR4_1_Reload_Handler,
    },
    Vector {
        _handler: TMR4_1_SCmp_Handler,
    },
    Vector {
        _handler: TMR4_2_GCmp_Handler,
    },
    Vector {
        _handler: TMR4_2_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMR4_2_Reload_Handler,
    },
    Vector {
        _handler: TMR4_2_SCmp_Handler,
    },
    Vector {
        _handler: TMR4_3_GCmp_Handler,
    },
    Vector {
        _handler: TMR4_3_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMR4_3_Reload_Handler,
    },
    Vector {
        _handler: TMR4_3_SCmp_Handler,
    },
    Vector {
        _handler: I2C1_Handler,
    },
    Vector {
        _handler: I2C2_Handler,
    },
    Vector {
        _handler: CMP1_Handler,
    },
    Vector {
        _handler: CMP2_Handler,
    },
    Vector {
        _handler: CMP3_Handler,
    },
    Vector {
        _handler: CMP4_Handler,
    },
    Vector {
        _handler: USART1_Handler,
    },
    Vector {
        _handler: USART1_TxComplete_Handler,
    },
    Vector {
        _handler: USART2_Handler,
    },
    Vector {
        _handler: USART2_TxComplete_Handler,
    },
    Vector {
        _handler: SPI1_Handler,
    },
    Vector {
        _handler: TMRA_5_Ovf_Udf_Handler,
    },
    Vector {
        _handler: TMRA_5_Cmp_Handler,
    },
    Vector {
        _handler: EVENT_PORT1_Handler,
    },
    Vector {
        _handler: EVENT_PORT2_Handler,
    },
    Vector {
        _handler: EVENT_PORT3_Handler,
    },
    Vector {
        _handler: EVENT_PORT4_Handler,
    },
    Vector {
        _handler: USART3_Handler,
    },
    Vector {
        _handler: USART3_TxComplete_Handler,
    },
    Vector {
        _handler: USART4_Handler,
    },
    Vector {
        _handler: USART4_TxComplete_Handler,
    },
    Vector {
        _handler: SPI2_Handler,
    },
    Vector {
        _handler: SPI3_Handler,
    },
    Vector {
        _handler: EMB_GR0_Handler,
    },
    Vector {
        _handler: EMB_GR1_Handler,
    },
    Vector {
        _handler: EMB_GR2_Handler,
    },
    Vector {
        _handler: EMB_GR3_Handler,
    },
    Vector {
        _handler: USART5_Handler,
    },
    Vector {
        _handler: USART6_Handler,
    },
    Vector { _reserved: 0 },
    Vector {
        _handler: USART6_TxComplete_Handler,
    },
    Vector {
        _handler: MCAN1_INT0_Handler,
    },
    Vector {
        _handler: MCAN1_INT1_Handler,
    },
    Vector {
        _handler: MCAN2_INT0_Handler,
    },
    Vector {
        _handler: MCAN2_INT1_Handler,
    },
    Vector {
        _handler: USART1_WKUP_Handler,
    },
    Vector {
        _handler: PWC_LVD1_Handler,
    },
    Vector {
        _handler: PWC_LVD2_Handler,
    },
    Vector {
        _handler: FCM_Handler,
    },
    Vector {
        _handler: WDT_Handler,
    },
    Vector {
        _handler: CTC_Handler,
    },
    Vector {
        _handler: ADC1_Handler,
    },
    Vector {
        _handler: ADC2_Handler,
    },
    Vector {
        _handler: ADC3_Handler,
    },
    Vector {
        _handler: TRNG_Handler,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - IRQ000_Handler"]
    IRQ000_Handler = 0,
    #[doc = "1 - IRQ001_Handler"]
    IRQ001_Handler = 1,
    #[doc = "2 - IRQ002_Handler"]
    IRQ002_Handler = 2,
    #[doc = "3 - IRQ003_Handler"]
    IRQ003_Handler = 3,
    #[doc = "4 - IRQ004_Handler"]
    IRQ004_Handler = 4,
    #[doc = "5 - IRQ005_Handler"]
    IRQ005_Handler = 5,
    #[doc = "6 - IRQ006_Handler"]
    IRQ006_Handler = 6,
    #[doc = "7 - IRQ007_Handler"]
    IRQ007_Handler = 7,
    #[doc = "8 - IRQ008_Handler"]
    IRQ008_Handler = 8,
    #[doc = "9 - IRQ009_Handler"]
    IRQ009_Handler = 9,
    #[doc = "10 - IRQ010_Handler"]
    IRQ010_Handler = 10,
    #[doc = "11 - IRQ011_Handler"]
    IRQ011_Handler = 11,
    #[doc = "12 - IRQ012_Handler"]
    IRQ012_Handler = 12,
    #[doc = "13 - IRQ013_Handler"]
    IRQ013_Handler = 13,
    #[doc = "14 - IRQ014_Handler"]
    IRQ014_Handler = 14,
    #[doc = "15 - IRQ015_Handler"]
    IRQ015_Handler = 15,
    #[doc = "16 - EXTINT00_SWINT16_Handler"]
    EXTINT00_SWINT16_Handler = 16,
    #[doc = "17 - EXTINT01_SWINT17_Handler"]
    EXTINT01_SWINT17_Handler = 17,
    #[doc = "18 - EXTINT02_SWINT18_Handler"]
    EXTINT02_SWINT18_Handler = 18,
    #[doc = "19 - EXTINT03_SWINT19_Handler"]
    EXTINT03_SWINT19_Handler = 19,
    #[doc = "20 - EXTINT04_SWINT20_Handler"]
    EXTINT04_SWINT20_Handler = 20,
    #[doc = "21 - EXTINT05_SWINT21_Handler"]
    EXTINT05_SWINT21_Handler = 21,
    #[doc = "22 - EXTINT06_SWINT22_Handler"]
    EXTINT06_SWINT22_Handler = 22,
    #[doc = "23 - EXTINT07_SWINT23_Handler"]
    EXTINT07_SWINT23_Handler = 23,
    #[doc = "24 - EXTINT08_SWINT24_Handler"]
    EXTINT08_SWINT24_Handler = 24,
    #[doc = "25 - EXTINT09_SWINT25_Handler"]
    EXTINT09_SWINT25_Handler = 25,
    #[doc = "26 - EXTINT10_SWINT26_Handler"]
    EXTINT10_SWINT26_Handler = 26,
    #[doc = "27 - EXTINT11_SWINT27_Handler"]
    EXTINT11_SWINT27_Handler = 27,
    #[doc = "28 - EXTINT12_SWINT28_Handler"]
    EXTINT12_SWINT28_Handler = 28,
    #[doc = "29 - EXTINT13_SWINT29_Handler"]
    EXTINT13_SWINT29_Handler = 29,
    #[doc = "30 - EXTINT14_SWINT30_Handler"]
    EXTINT14_SWINT30_Handler = 30,
    #[doc = "31 - EXTINT15_SWINT31_Handler"]
    EXTINT15_SWINT31_Handler = 31,
    #[doc = "32 - DMA1_Error_Handler"]
    DMA1_Error_Handler = 32,
    #[doc = "33 - DMA1_TC0_BTC0_Handler"]
    DMA1_TC0_BTC0_Handler = 33,
    #[doc = "34 - DMA1_TC1_BTC1_Handler"]
    DMA1_TC1_BTC1_Handler = 34,
    #[doc = "35 - DMA1_TC2_BTC2_Handler"]
    DMA1_TC2_BTC2_Handler = 35,
    #[doc = "36 - DMA1_TC3_BTC3_Handler"]
    DMA1_TC3_BTC3_Handler = 36,
    #[doc = "37 - DMA1_TC4_BTC4_Handler"]
    DMA1_TC4_BTC4_Handler = 37,
    #[doc = "38 - DMA1_TC5_BTC5_Handler"]
    DMA1_TC5_BTC5_Handler = 38,
    #[doc = "39 - EFM_PEError_ReadCol_Handler"]
    EFM_PEError_ReadCol_Handler = 39,
    #[doc = "40 - EFM_OpEnd_Handler"]
    EFM_OpEnd_Handler = 40,
    #[doc = "41 - QSPI_Handler"]
    QSPI_Handler = 41,
    #[doc = "42 - DCU1_Handler"]
    DCU1_Handler = 42,
    #[doc = "43 - DCU2_Handler"]
    DCU2_Handler = 43,
    #[doc = "44 - DCU3_Handler"]
    DCU3_Handler = 44,
    #[doc = "45 - DCU4_Handler"]
    DCU4_Handler = 45,
    #[doc = "46 - DMA2_Error_Handler"]
    DMA2_Error_Handler = 46,
    #[doc = "47 - DMA2_TC0_BTC0_Handler"]
    DMA2_TC0_BTC0_Handler = 47,
    #[doc = "48 - DMA2_TC1_BTC1_Handler"]
    DMA2_TC1_BTC1_Handler = 48,
    #[doc = "49 - DMA2_TC2_BTC2_Handler"]
    DMA2_TC2_BTC2_Handler = 49,
    #[doc = "50 - DMA2_TC3_BTC3_Handler"]
    DMA2_TC3_BTC3_Handler = 50,
    #[doc = "51 - DMA2_TC4_BTC4_Handler"]
    DMA2_TC4_BTC4_Handler = 51,
    #[doc = "52 - DMA2_TC5_BTC5_Handler"]
    DMA2_TC5_BTC5_Handler = 52,
    #[doc = "53 - TMR0_1_Handler"]
    TMR0_1_Handler = 53,
    #[doc = "54 - TMR0_2_Handler"]
    TMR0_2_Handler = 54,
    #[doc = "55 - RTC_Handler"]
    RTC_Handler = 55,
    #[doc = "56 - CLK_XtalStop_Handler"]
    CLK_XtalStop_Handler = 56,
    #[doc = "57 - PWC_WKTM_Handler"]
    PWC_WKTM_Handler = 57,
    #[doc = "58 - SWDT_Handler"]
    SWDT_Handler = 58,
    #[doc = "59 - TMR6_1_GCmp_Handler"]
    TMR6_1_GCmp_Handler = 59,
    #[doc = "60 - TMR6_1_Ovf_Udf_Handler"]
    TMR6_1_Ovf_Udf_Handler = 60,
    #[doc = "61 - TMR6_1_Dte_Handler"]
    TMR6_1_Dte_Handler = 61,
    #[doc = "62 - TMR6_1_SCmp_Handler"]
    TMR6_1_SCmp_Handler = 62,
    #[doc = "63 - TMRA_1_Ovf_Udf_Handler"]
    TMRA_1_Ovf_Udf_Handler = 63,
    #[doc = "64 - TMRA_1_Cmp_Handler"]
    TMRA_1_Cmp_Handler = 64,
    #[doc = "65 - TMR6_2_GCmp_Handler"]
    TMR6_2_GCmp_Handler = 65,
    #[doc = "66 - TMR6_2_Ovf_Udf_Handler"]
    TMR6_2_Ovf_Udf_Handler = 66,
    #[doc = "67 - TMR6_2_Dte_Handler"]
    TMR6_2_Dte_Handler = 67,
    #[doc = "68 - TMR6_2_SCmp_Handler"]
    TMR6_2_SCmp_Handler = 68,
    #[doc = "69 - TMRA_2_Ovf_Udf_Handler"]
    TMRA_2_Ovf_Udf_Handler = 69,
    #[doc = "70 - TMRA_2_Cmp_Handler"]
    TMRA_2_Cmp_Handler = 70,
    #[doc = "71 - TMRA_3_Ovf_Udf_Handler"]
    TMRA_3_Ovf_Udf_Handler = 71,
    #[doc = "72 - TMRA_3_Cmp_Handler"]
    TMRA_3_Cmp_Handler = 72,
    #[doc = "73 - TMRA_4_Ovf_Udf_Handler"]
    TMRA_4_Ovf_Udf_Handler = 73,
    #[doc = "74 - TMRA_4_Cmp_Handler"]
    TMRA_4_Cmp_Handler = 74,
    #[doc = "75 - TMR4_1_GCmp_Handler"]
    TMR4_1_GCmp_Handler = 75,
    #[doc = "76 - TMR4_1_Ovf_Udf_Handler"]
    TMR4_1_Ovf_Udf_Handler = 76,
    #[doc = "77 - TMR4_1_Reload_Handler"]
    TMR4_1_Reload_Handler = 77,
    #[doc = "78 - TMR4_1_SCmp_Handler"]
    TMR4_1_SCmp_Handler = 78,
    #[doc = "79 - TMR4_2_GCmp_Handler"]
    TMR4_2_GCmp_Handler = 79,
    #[doc = "80 - TMR4_2_Ovf_Udf_Handler"]
    TMR4_2_Ovf_Udf_Handler = 80,
    #[doc = "81 - TMR4_2_Reload_Handler"]
    TMR4_2_Reload_Handler = 81,
    #[doc = "82 - TMR4_2_SCmp_Handler"]
    TMR4_2_SCmp_Handler = 82,
    #[doc = "83 - TMR4_3_GCmp_Handler"]
    TMR4_3_GCmp_Handler = 83,
    #[doc = "84 - TMR4_3_Ovf_Udf_Handler"]
    TMR4_3_Ovf_Udf_Handler = 84,
    #[doc = "85 - TMR4_3_Reload_Handler"]
    TMR4_3_Reload_Handler = 85,
    #[doc = "86 - TMR4_3_SCmp_Handler"]
    TMR4_3_SCmp_Handler = 86,
    #[doc = "87 - I2C1_Handler"]
    I2C1_Handler = 87,
    #[doc = "88 - I2C2_Handler"]
    I2C2_Handler = 88,
    #[doc = "89 - CMP1_Handler"]
    CMP1_Handler = 89,
    #[doc = "90 - CMP2_Handler"]
    CMP2_Handler = 90,
    #[doc = "91 - CMP3_Handler"]
    CMP3_Handler = 91,
    #[doc = "92 - CMP4_Handler"]
    CMP4_Handler = 92,
    #[doc = "93 - USART1_Handler"]
    USART1_Handler = 93,
    #[doc = "94 - USART1_TxComplete_Handler"]
    USART1_TxComplete_Handler = 94,
    #[doc = "95 - USART2_Handler"]
    USART2_Handler = 95,
    #[doc = "96 - USART2_TxComplete_Handler"]
    USART2_TxComplete_Handler = 96,
    #[doc = "97 - SPI1_Handler"]
    SPI1_Handler = 97,
    #[doc = "98 - TMRA_5_Ovf_Udf_Handler"]
    TMRA_5_Ovf_Udf_Handler = 98,
    #[doc = "99 - TMRA_5_Cmp_Handler"]
    TMRA_5_Cmp_Handler = 99,
    #[doc = "100 - EVENT_PORT1_Handler"]
    EVENT_PORT1_Handler = 100,
    #[doc = "101 - EVENT_PORT2_Handler"]
    EVENT_PORT2_Handler = 101,
    #[doc = "102 - EVENT_PORT3_Handler"]
    EVENT_PORT3_Handler = 102,
    #[doc = "103 - EVENT_PORT4_Handler"]
    EVENT_PORT4_Handler = 103,
    #[doc = "104 - USART3_Handler"]
    USART3_Handler = 104,
    #[doc = "105 - USART3_TxComplete_Handler"]
    USART3_TxComplete_Handler = 105,
    #[doc = "106 - USART4_Handler"]
    USART4_Handler = 106,
    #[doc = "107 - USART4_TxComplete_Handler"]
    USART4_TxComplete_Handler = 107,
    #[doc = "108 - SPI2_Handler"]
    SPI2_Handler = 108,
    #[doc = "109 - SPI3_Handler"]
    SPI3_Handler = 109,
    #[doc = "110 - EMB_GR0_Handler"]
    EMB_GR0_Handler = 110,
    #[doc = "111 - EMB_GR1_Handler"]
    EMB_GR1_Handler = 111,
    #[doc = "112 - EMB_GR2_Handler"]
    EMB_GR2_Handler = 112,
    #[doc = "113 - EMB_GR3_Handler"]
    EMB_GR3_Handler = 113,
    #[doc = "114 - USART5_Handler"]
    USART5_Handler = 114,
    #[doc = "115 - USART6_Handler"]
    USART6_Handler = 115,
    #[doc = "117 - USART6_TxComplete_Handler"]
    USART6_TxComplete_Handler = 117,
    #[doc = "118 - MCAN1_INT0_Handler"]
    MCAN1_INT0_Handler = 118,
    #[doc = "119 - MCAN1_INT1_Handler"]
    MCAN1_INT1_Handler = 119,
    #[doc = "120 - MCAN2_INT0_Handler"]
    MCAN2_INT0_Handler = 120,
    #[doc = "121 - MCAN2_INT1_Handler"]
    MCAN2_INT1_Handler = 121,
    #[doc = "122 - USART1_WKUP_Handler"]
    USART1_WKUP_Handler = 122,
    #[doc = "123 - PWC_LVD1_Handler"]
    PWC_LVD1_Handler = 123,
    #[doc = "124 - PWC_LVD2_Handler"]
    PWC_LVD2_Handler = 124,
    #[doc = "125 - FCM_Handler"]
    FCM_Handler = 125,
    #[doc = "126 - WDT_Handler"]
    WDT_Handler = 126,
    #[doc = "127 - CTC_Handler"]
    CTC_Handler = 127,
    #[doc = "128 - ADC1_Handler"]
    ADC1_Handler = 128,
    #[doc = "129 - ADC2_Handler"]
    ADC2_Handler = 129,
    #[doc = "130 - ADC3_Handler"]
    ADC3_Handler = 130,
    #[doc = "131 - TRNG_Handler"]
    TRNG_Handler = 131,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "desc ADC1"]
pub type Adc1 = crate::Periph<adc1::RegisterBlock, 0x4004_0000>;
impl core::fmt::Debug for Adc1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc1").finish()
    }
}
#[doc = "desc ADC1"]
pub mod adc1;
#[doc = "desc ADC2"]
pub type Adc2 = crate::Periph<adc2::RegisterBlock, 0x4004_0400>;
impl core::fmt::Debug for Adc2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc2").finish()
    }
}
#[doc = "desc ADC2"]
pub mod adc2;
#[doc = "desc ADC3"]
pub type Adc3 = crate::Periph<adc3::RegisterBlock, 0x4004_0800>;
impl core::fmt::Debug for Adc3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc3").finish()
    }
}
#[doc = "desc ADC3"]
pub mod adc3;
#[doc = "desc AES"]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "desc AES"]
pub mod aes;
#[doc = "desc AOS"]
pub type Aos = crate::Periph<aos::RegisterBlock, 0x4001_0800>;
impl core::fmt::Debug for Aos {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aos").finish()
    }
}
#[doc = "desc AOS"]
pub mod aos;
#[doc = "desc CMP1"]
pub type Cmp1 = crate::Periph<cmp1::RegisterBlock, 0x4003_8800>;
impl core::fmt::Debug for Cmp1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp1").finish()
    }
}
#[doc = "desc CMP1"]
pub mod cmp1;
#[doc = "desc CMP2"]
pub type Cmp2 = crate::Periph<cmp2::RegisterBlock, 0x4003_8900>;
impl core::fmt::Debug for Cmp2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp2").finish()
    }
}
#[doc = "desc CMP2"]
pub mod cmp2;
#[doc = "desc CMP3"]
pub type Cmp3 = crate::Periph<cmp3::RegisterBlock, 0x4003_8c00>;
impl core::fmt::Debug for Cmp3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp3").finish()
    }
}
#[doc = "desc CMP3"]
pub mod cmp3;
#[doc = "desc CMP4"]
pub type Cmp4 = crate::Periph<cmp4::RegisterBlock, 0x4003_8d00>;
impl core::fmt::Debug for Cmp4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp4").finish()
    }
}
#[doc = "desc CMP4"]
pub mod cmp4;
#[doc = "desc CMU"]
pub type Cmu = crate::Periph<cmu::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for Cmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmu").finish()
    }
}
#[doc = "desc CMU"]
pub mod cmu;
#[doc = "desc CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4000_8c00>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "desc CRC"]
pub mod crc;
#[doc = "desc CTC"]
pub type Ctc = crate::Periph<ctc::RegisterBlock, 0x4004_9c00>;
impl core::fmt::Debug for Ctc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctc").finish()
    }
}
#[doc = "desc CTC"]
pub mod ctc;
#[doc = "desc DAC"]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x4004_1000>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "desc DAC"]
pub mod dac;
#[doc = "desc DBGC"]
pub type Dbgc = crate::Periph<dbgc::RegisterBlock, 0xe004_2000>;
impl core::fmt::Debug for Dbgc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbgc").finish()
    }
}
#[doc = "desc DBGC"]
pub mod dbgc;
#[doc = "desc DCU"]
pub type Dcu1 = crate::Periph<dcu1::RegisterBlock, 0x4005_6000>;
impl core::fmt::Debug for Dcu1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu1").finish()
    }
}
#[doc = "desc DCU"]
pub mod dcu1;
#[doc = "desc DCU"]
pub type Dcu2 = crate::Periph<dcu1::RegisterBlock, 0x4005_6400>;
impl core::fmt::Debug for Dcu2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu2").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu2;
#[doc = "desc DCU"]
pub type Dcu3 = crate::Periph<dcu1::RegisterBlock, 0x4005_6800>;
impl core::fmt::Debug for Dcu3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu3").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu3;
#[doc = "desc DCU"]
pub type Dcu4 = crate::Periph<dcu1::RegisterBlock, 0x4005_6c00>;
impl core::fmt::Debug for Dcu4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dcu4").finish()
    }
}
#[doc = "desc DCU"]
pub use self::dcu1 as dcu4;
#[doc = "desc DMA"]
pub type Dma1 = crate::Periph<dma1::RegisterBlock, 0x4005_3000>;
impl core::fmt::Debug for Dma1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma1").finish()
    }
}
#[doc = "desc DMA"]
pub mod dma1;
#[doc = "desc DMA"]
pub type Dma2 = crate::Periph<dma1::RegisterBlock, 0x4005_3400>;
impl core::fmt::Debug for Dma2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma2").finish()
    }
}
#[doc = "desc DMA"]
pub use self::dma1 as dma2;
#[doc = "desc EFM"]
pub type Efm = crate::Periph<efm::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Efm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Efm").finish()
    }
}
#[doc = "desc EFM"]
pub mod efm;
#[doc = "desc EMB0"]
pub type Emb0 = crate::Periph<emb0::RegisterBlock, 0x4001_7c00>;
impl core::fmt::Debug for Emb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb0").finish()
    }
}
#[doc = "desc EMB0"]
pub mod emb0;
#[doc = "desc EMB"]
pub type Emb1 = crate::Periph<emb1::RegisterBlock, 0x4001_7c20>;
impl core::fmt::Debug for Emb1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb1").finish()
    }
}
#[doc = "desc EMB"]
pub mod emb1;
#[doc = "desc EMB"]
pub type Emb2 = crate::Periph<emb1::RegisterBlock, 0x4001_7c40>;
impl core::fmt::Debug for Emb2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb2").finish()
    }
}
#[doc = "desc EMB"]
pub use self::emb1 as emb2;
#[doc = "desc EMB"]
pub type Emb3 = crate::Periph<emb1::RegisterBlock, 0x4001_7c60>;
impl core::fmt::Debug for Emb3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Emb3").finish()
    }
}
#[doc = "desc EMB"]
pub use self::emb1 as emb3;
#[doc = "desc FCM"]
pub type Fcm = crate::Periph<fcm::RegisterBlock, 0x4004_8400>;
impl core::fmt::Debug for Fcm {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fcm").finish()
    }
}
#[doc = "desc FCM"]
pub mod fcm;
#[doc = "desc GPIO"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x4005_3800>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "desc GPIO"]
pub mod gpio;
#[doc = "desc HASH"]
pub type Hash = crate::Periph<hash::RegisterBlock, 0x4000_8400>;
impl core::fmt::Debug for Hash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hash").finish()
    }
}
#[doc = "desc HASH"]
pub mod hash;
#[doc = "desc I2C"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4003_b400>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "desc I2C"]
pub mod i2c1;
#[doc = "desc I2C"]
pub type I2c2 = crate::Periph<i2c1::RegisterBlock, 0x4003_b800>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "desc I2C"]
pub use self::i2c1 as i2c2;
#[doc = "desc ICG"]
pub type Icg = crate::Periph<icg::RegisterBlock, 0x0400>;
impl core::fmt::Debug for Icg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Icg").finish()
    }
}
#[doc = "desc ICG"]
pub mod icg;
#[doc = "desc INTC"]
pub type Intc = crate::Periph<intc::RegisterBlock, 0x4005_1000>;
impl core::fmt::Debug for Intc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Intc").finish()
    }
}
#[doc = "desc INTC"]
pub mod intc;
#[doc = "desc KEYSCAN"]
pub type Keyscan = crate::Periph<keyscan::RegisterBlock, 0x4005_0c00>;
impl core::fmt::Debug for Keyscan {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Keyscan").finish()
    }
}
#[doc = "desc KEYSCAN"]
pub mod keyscan;
#[doc = "desc MCAN"]
pub type Mcan1 = crate::Periph<mcan1::RegisterBlock, 0x4002_9000>;
impl core::fmt::Debug for Mcan1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcan1").finish()
    }
}
#[doc = "desc MCAN"]
pub mod mcan1;
#[doc = "desc MCAN"]
pub type Mcan2 = crate::Periph<mcan1::RegisterBlock, 0x4002_9400>;
impl core::fmt::Debug for Mcan2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mcan2").finish()
    }
}
#[doc = "desc MCAN"]
pub use self::mcan1 as mcan2;
#[doc = "desc PERIC"]
pub type Peric = crate::Periph<peric::RegisterBlock, 0x4005_5400>;
impl core::fmt::Debug for Peric {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Peric").finish()
    }
}
#[doc = "desc PERIC"]
pub mod peric;
#[doc = "desc PWC"]
pub type Pwc = crate::Periph<pwc::RegisterBlock, 0x4004_8000>;
impl core::fmt::Debug for Pwc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwc").finish()
    }
}
#[doc = "desc PWC"]
pub mod pwc;
#[doc = "desc QSPI"]
pub type Qspi = crate::Periph<qspi::RegisterBlock, 0x9c00_0000>;
impl core::fmt::Debug for Qspi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Qspi").finish()
    }
}
#[doc = "desc QSPI"]
pub mod qspi;
#[doc = "desc RMU"]
pub type Rmu = crate::Periph<rmu::RegisterBlock, 0x4004_cce0>;
impl core::fmt::Debug for Rmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rmu").finish()
    }
}
#[doc = "desc RMU"]
pub mod rmu;
#[doc = "desc RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4004_c000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "desc RTC"]
pub mod rtc;
#[doc = "desc SMC"]
pub type Smc = crate::Periph<smc::RegisterBlock, 0x8800_0000>;
impl core::fmt::Debug for Smc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Smc").finish()
    }
}
#[doc = "desc SMC"]
pub mod smc;
#[doc = "desc SPI"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4001_c000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "desc SPI"]
pub mod spi1;
#[doc = "desc SPI"]
pub type Spi2 = crate::Periph<spi1::RegisterBlock, 0x4001_c400>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "desc SPI"]
pub use self::spi1 as spi2;
#[doc = "desc SPI"]
pub type Spi3 = crate::Periph<spi1::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "desc SPI"]
pub use self::spi1 as spi3;
#[doc = "desc SRAMC"]
pub type Sramc = crate::Periph<sramc::RegisterBlock, 0x4005_0800>;
impl core::fmt::Debug for Sramc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sramc").finish()
    }
}
#[doc = "desc SRAMC"]
pub mod sramc;
#[doc = "desc SWDT"]
pub type Swdt = crate::Periph<swdt::RegisterBlock, 0x4004_9400>;
impl core::fmt::Debug for Swdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Swdt").finish()
    }
}
#[doc = "desc SWDT"]
pub mod swdt;
#[doc = "desc TMR0"]
pub type Tmr01 = crate::Periph<tmr01::RegisterBlock, 0x4002_4000>;
impl core::fmt::Debug for Tmr01 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr01").finish()
    }
}
#[doc = "desc TMR0"]
pub mod tmr01;
#[doc = "desc TMR0"]
pub type Tmr02 = crate::Periph<tmr01::RegisterBlock, 0x4002_4400>;
impl core::fmt::Debug for Tmr02 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr02").finish()
    }
}
#[doc = "desc TMR0"]
pub use self::tmr01 as tmr02;
#[doc = "desc TMR41"]
pub type Tmr41 = crate::Periph<tmr41::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for Tmr41 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr41").finish()
    }
}
#[doc = "desc TMR41"]
pub mod tmr41;
#[doc = "desc TMR42"]
pub type Tmr42 = crate::Periph<tmr42::RegisterBlock, 0x4003_8400>;
impl core::fmt::Debug for Tmr42 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr42").finish()
    }
}
#[doc = "desc TMR42"]
pub mod tmr42;
#[doc = "desc TMR43"]
pub type Tmr43 = crate::Periph<tmr43::RegisterBlock, 0x4003_8e00>;
impl core::fmt::Debug for Tmr43 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr43").finish()
    }
}
#[doc = "desc TMR43"]
pub mod tmr43;
#[doc = "desc TMR6"]
pub type Tmr61 = crate::Periph<tmr61::RegisterBlock, 0x4003_c000>;
impl core::fmt::Debug for Tmr61 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr61").finish()
    }
}
#[doc = "desc TMR6"]
pub mod tmr61;
#[doc = "desc TMR6"]
pub type Tmr62 = crate::Periph<tmr61::RegisterBlock, 0x4003_c400>;
impl core::fmt::Debug for Tmr62 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr62").finish()
    }
}
#[doc = "desc TMR6"]
pub use self::tmr61 as tmr62;
#[doc = "desc TMR6_COMMON"]
pub type Tmr6Common = crate::Periph<tmr6_common::RegisterBlock, 0x4003_c300>;
impl core::fmt::Debug for Tmr6Common {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmr6Common").finish()
    }
}
#[doc = "desc TMR6_COMMON"]
pub mod tmr6_common;
#[doc = "desc TMRA"]
pub type Tmra1 = crate::Periph<tmra1::RegisterBlock, 0x4003_a000>;
impl core::fmt::Debug for Tmra1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra1").finish()
    }
}
#[doc = "desc TMRA"]
pub mod tmra1;
#[doc = "desc TMRA"]
pub type Tmra2 = crate::Periph<tmra1::RegisterBlock, 0x4003_a400>;
impl core::fmt::Debug for Tmra2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra2").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra2;
#[doc = "desc TMRA"]
pub type Tmra3 = crate::Periph<tmra1::RegisterBlock, 0x4003_a800>;
impl core::fmt::Debug for Tmra3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra3").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra3;
#[doc = "desc TMRA"]
pub type Tmra4 = crate::Periph<tmra1::RegisterBlock, 0x4003_ac00>;
impl core::fmt::Debug for Tmra4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra4").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra4;
#[doc = "desc TMRA"]
pub type Tmra5 = crate::Periph<tmra1::RegisterBlock, 0x4002_6000>;
impl core::fmt::Debug for Tmra5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tmra5").finish()
    }
}
#[doc = "desc TMRA"]
pub use self::tmra1 as tmra5;
#[doc = "desc TRNG"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4004_2000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "desc TRNG"]
pub mod trng;
#[doc = "desc USART"]
pub type Usart1 = crate::Periph<usart1::RegisterBlock, 0x4001_cc00>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "desc USART"]
pub mod usart1;
#[doc = "desc USART"]
pub type Usart2 = crate::Periph<usart1::RegisterBlock, 0x4001_d000>;
impl core::fmt::Debug for Usart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart2").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart2;
#[doc = "desc USART"]
pub type Usart3 = crate::Periph<usart3::RegisterBlock, 0x4001_d400>;
impl core::fmt::Debug for Usart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart3").finish()
    }
}
#[doc = "desc USART"]
pub mod usart3;
#[doc = "desc USART"]
pub type Usart4 = crate::Periph<usart1::RegisterBlock, 0x4002_0c00>;
impl core::fmt::Debug for Usart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart4").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart4;
#[doc = "desc USART"]
pub type Usart5 = crate::Periph<usart1::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Usart5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart5").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart1 as usart5;
#[doc = "desc USART"]
pub type Usart6 = crate::Periph<usart3::RegisterBlock, 0x4002_1400>;
impl core::fmt::Debug for Usart6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart6").finish()
    }
}
#[doc = "desc USART"]
pub use self::usart3 as usart6;
#[doc = "desc WDT"]
pub type Wdt = crate::Periph<wdt::RegisterBlock, 0x4004_9000>;
impl core::fmt::Debug for Wdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wdt").finish()
    }
}
#[doc = "desc WDT"]
pub mod wdt;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC1"]
    pub adc1: Adc1,
    #[doc = "ADC2"]
    pub adc2: Adc2,
    #[doc = "ADC3"]
    pub adc3: Adc3,
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "AOS"]
    pub aos: Aos,
    #[doc = "CMP1"]
    pub cmp1: Cmp1,
    #[doc = "CMP2"]
    pub cmp2: Cmp2,
    #[doc = "CMP3"]
    pub cmp3: Cmp3,
    #[doc = "CMP4"]
    pub cmp4: Cmp4,
    #[doc = "CMU"]
    pub cmu: Cmu,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "CTC"]
    pub ctc: Ctc,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "DBGC"]
    pub dbgc: Dbgc,
    #[doc = "DCU1"]
    pub dcu1: Dcu1,
    #[doc = "DCU2"]
    pub dcu2: Dcu2,
    #[doc = "DCU3"]
    pub dcu3: Dcu3,
    #[doc = "DCU4"]
    pub dcu4: Dcu4,
    #[doc = "DMA1"]
    pub dma1: Dma1,
    #[doc = "DMA2"]
    pub dma2: Dma2,
    #[doc = "EFM"]
    pub efm: Efm,
    #[doc = "EMB0"]
    pub emb0: Emb0,
    #[doc = "EMB1"]
    pub emb1: Emb1,
    #[doc = "EMB2"]
    pub emb2: Emb2,
    #[doc = "EMB3"]
    pub emb3: Emb3,
    #[doc = "FCM"]
    pub fcm: Fcm,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "HASH"]
    pub hash: Hash,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "ICG"]
    pub icg: Icg,
    #[doc = "INTC"]
    pub intc: Intc,
    #[doc = "KEYSCAN"]
    pub keyscan: Keyscan,
    #[doc = "MCAN1"]
    pub mcan1: Mcan1,
    #[doc = "MCAN2"]
    pub mcan2: Mcan2,
    #[doc = "PERIC"]
    pub peric: Peric,
    #[doc = "PWC"]
    pub pwc: Pwc,
    #[doc = "QSPI"]
    pub qspi: Qspi,
    #[doc = "RMU"]
    pub rmu: Rmu,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SMC"]
    pub smc: Smc,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SRAMC"]
    pub sramc: Sramc,
    #[doc = "SWDT"]
    pub swdt: Swdt,
    #[doc = "TMR01"]
    pub tmr01: Tmr01,
    #[doc = "TMR02"]
    pub tmr02: Tmr02,
    #[doc = "TMR41"]
    pub tmr41: Tmr41,
    #[doc = "TMR42"]
    pub tmr42: Tmr42,
    #[doc = "TMR43"]
    pub tmr43: Tmr43,
    #[doc = "TMR61"]
    pub tmr61: Tmr61,
    #[doc = "TMR62"]
    pub tmr62: Tmr62,
    #[doc = "TMR6_COMMON"]
    pub tmr6_common: Tmr6Common,
    #[doc = "TMRA1"]
    pub tmra1: Tmra1,
    #[doc = "TMRA2"]
    pub tmra2: Tmra2,
    #[doc = "TMRA3"]
    pub tmra3: Tmra3,
    #[doc = "TMRA4"]
    pub tmra4: Tmra4,
    #[doc = "TMRA5"]
    pub tmra5: Tmra5,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "USART2"]
    pub usart2: Usart2,
    #[doc = "USART3"]
    pub usart3: Usart3,
    #[doc = "USART4"]
    pub usart4: Usart4,
    #[doc = "USART5"]
    pub usart5: Usart5,
    #[doc = "USART6"]
    pub usart6: Usart6,
    #[doc = "WDT"]
    pub wdt: Wdt,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            adc1: unsafe { Adc1::steal() },
            adc2: unsafe { Adc2::steal() },
            adc3: unsafe { Adc3::steal() },
            aes: unsafe { Aes::steal() },
            aos: unsafe { Aos::steal() },
            cmp1: unsafe { Cmp1::steal() },
            cmp2: unsafe { Cmp2::steal() },
            cmp3: unsafe { Cmp3::steal() },
            cmp4: unsafe { Cmp4::steal() },
            cmu: unsafe { Cmu::steal() },
            crc: unsafe { Crc::steal() },
            ctc: unsafe { Ctc::steal() },
            dac: unsafe { Dac::steal() },
            dbgc: unsafe { Dbgc::steal() },
            dcu1: unsafe { Dcu1::steal() },
            dcu2: unsafe { Dcu2::steal() },
            dcu3: unsafe { Dcu3::steal() },
            dcu4: unsafe { Dcu4::steal() },
            dma1: unsafe { Dma1::steal() },
            dma2: unsafe { Dma2::steal() },
            efm: unsafe { Efm::steal() },
            emb0: unsafe { Emb0::steal() },
            emb1: unsafe { Emb1::steal() },
            emb2: unsafe { Emb2::steal() },
            emb3: unsafe { Emb3::steal() },
            fcm: unsafe { Fcm::steal() },
            gpio: unsafe { Gpio::steal() },
            hash: unsafe { Hash::steal() },
            i2c1: unsafe { I2c1::steal() },
            i2c2: unsafe { I2c2::steal() },
            icg: unsafe { Icg::steal() },
            intc: unsafe { Intc::steal() },
            keyscan: unsafe { Keyscan::steal() },
            mcan1: unsafe { Mcan1::steal() },
            mcan2: unsafe { Mcan2::steal() },
            peric: unsafe { Peric::steal() },
            pwc: unsafe { Pwc::steal() },
            qspi: unsafe { Qspi::steal() },
            rmu: unsafe { Rmu::steal() },
            rtc: unsafe { Rtc::steal() },
            smc: unsafe { Smc::steal() },
            spi1: unsafe { Spi1::steal() },
            spi2: unsafe { Spi2::steal() },
            spi3: unsafe { Spi3::steal() },
            sramc: unsafe { Sramc::steal() },
            swdt: unsafe { Swdt::steal() },
            tmr01: unsafe { Tmr01::steal() },
            tmr02: unsafe { Tmr02::steal() },
            tmr41: unsafe { Tmr41::steal() },
            tmr42: unsafe { Tmr42::steal() },
            tmr43: unsafe { Tmr43::steal() },
            tmr61: unsafe { Tmr61::steal() },
            tmr62: unsafe { Tmr62::steal() },
            tmr6_common: unsafe { Tmr6Common::steal() },
            tmra1: unsafe { Tmra1::steal() },
            tmra2: unsafe { Tmra2::steal() },
            tmra3: unsafe { Tmra3::steal() },
            tmra4: unsafe { Tmra4::steal() },
            tmra5: unsafe { Tmra5::steal() },
            trng: unsafe { Trng::steal() },
            usart1: unsafe { Usart1::steal() },
            usart2: unsafe { Usart2::steal() },
            usart3: unsafe { Usart3::steal() },
            usart4: unsafe { Usart4::steal() },
            usart5: unsafe { Usart5::steal() },
            usart6: unsafe { Usart6::steal() },
            wdt: unsafe { Wdt::steal() },
        }
    }
}
